apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-creative-studio
resources:
  - k8s
configMapGenerator:
  - name: studio-config
    files:
      - config.yaml
images:
  - name: ai-creative-studio
    newName: ai-creative-studio
    newTag: latest
