apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-creative-studio
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: studio-config
    files:
      - config.yaml=../config.yaml
images:
  - name: ai-creative-studio
    newName: ai-creative-studio
    newTag: latest
